services:
  client:
    build:
      context: client
      args:
        NEXT_PUBLIC_BACKEND_URL: ${SERVER_URL}
        NEXT_PUBLIC_CONTRACT_ID: ${CONTRACT_ID}
        SOROBAN_RPC_URL: ${SOROBAN_RPC_URL}
        NETWORK_PASSPHASE: ${NETWORK_PASSPHASE}
        HORIZON_URL: ${HORIZON_URL}
    container_name: votex-client
    env_file:
      - client/.env.docker
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - server

  server:
    build:
      context: server
    container_name: votex-server
    env_file:
      - server/.env.docker
    environment:
      - CONTRACT_ID=${CONTRACT_ID}
    networks:
      - app-network
    ports:
      - 8080:8080
    depends_on:
      - redis

  stellar:
    image: stellar/quickstart:v455-latest
    container_name: votex-stellar
    ports:
      - "8000:8000"
      - "11625:11625"
      - "11626:11626"
      - "5432:5432"
      - "6060:6060"
      - "6061:6061"
    environment:
      - POSTGRES_PASSWORD=${STELLAR_POSTGRES_PASSWORD}
      - HORIZON_CORS_ALLOWED_ORIGINS=*
      - SOROBAN_RPC_ENABLED=true
      - PROTOCOL_VERSION=22
      - LIMITS=unlimited
      - NETWORK=local
      - STELLAR_MODE=persistent
    volumes:
      - ./web3/scripts/health-check.sh:/opt/stellar/bin/health-check.sh
      # - stellar_data:/opt/stellar
      # - stellar_postgres_data:/var/lib/postgresql
      # - stellar_history_data:/tmp/stellar-core/history
    cap_add:
      - IPC_LOCK
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/opt/stellar/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  redis:
    image: redis/redis-stack:latest
    container_name: votex-redis
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_DATABASE_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  redis_data:
  # stellar_data:
  # stellar_postgres_data:
  # stellar_history_data:

networks:
  app-network:
    driver: bridge
